apiVersion: constraints.gatekeeper.sh/v1beta1
kind: DataProtectionRequiredLabels
metadata:
  name: prod-must-have-dp-labels
spec:
  match:
    kinds:
      - apiGroups: ["apps"] # monitor only app resources like below
        kinds: ["Deployment","StatefulSet"]
  parameters:
    labels: ["dataprotection","immutable"] # does not validate label values, only existence of labels