apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-gold-backup-policy
  annotations:
    policies.kyverno.io/title: Generate Gold Backup Policy
    policies.kyverno.io/category: K10
    policies.kyverno.io/subject: Policy
    policies.kyverno.io/description: >-
      Generate a backup policy for any Deployment or StatefulSet that adds the labels "dataprotection: k10-goldpolicy"
      This policy works best to decide the data protection objectives and simply assign backup via application labels.
spec:
  background: false
  rules:
  - name: "generate-gold-backup-policy"
    match:
      resources:
        kinds:
          - Deployment
          - StatefulSet
        selector:
          matchLabels:
            dataprotection: k10-goldpolicy # match with a corresponding ClusterPolicy that checks for this label
    generate:
      apiVersion: config.kio.kasten.io/v1alpha1
      kind: Policy
      name: k10-{{request.namespace}}-gold-backup-policy
      namespace: "{{request.namespace}}"
      data:   
        metadata: 
          name: k10-{{request.namespace}}-gold-backup-policy
          namespace: "{{request.namespace}}"
        spec:
          comment: K10 "gold" immutable production backup policy
          frequency: '@daily'
          subFrequency:
            minutes: [30]
            hours: [24,7]
            weekdays: [5]
            days: [15]
          retention:
            daily: 7
            weekly: 4
            monthly: 12
            yearly: 7
          actions:
          - action: backup
          - action: export
            exportParameters:
              frequency: '@monthly'
              profile:
                name: immutable-location-profile
                namespace: kasten-io
              exportData:
                enabled: true
            retention:
              monthly: 12
              yearly: 5
          selector:
            matchExpressions:
              - key: k10.kasten.io/appNamespace
                operator: In
                values:
                  - "{{request.namespace}}"